"""Update table models

Revision ID: 1eeab6fe2e86
Revises: 4f8350fbc33c
Create Date: 2026-07-07 19:41:02.528455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eeab6fe2e86'
down_revision: Union[str, Sequence[str], None] = '4f8350fbc33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('api_usage', sa.Column('model_version_id', sa.Integer(), nullable=False))
    op.add_column('api_usage', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('api_usage_model_id_fkey'), 'api_usage', type_='foreignkey')
    op.create_foreign_key(None, 'api_usage', 'model_versions', ['model_version_id'], ['id'])
    op.drop_column('api_usage', 'model_id')
    op.add_column('models', sa.Column('description', sa.String(), nullable=True))
    op.add_column('models', sa.Column('task', sa.Enum('TEXT_GENERATION', name='task_type_enum'), nullable=False))
    op.add_column('models', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('models', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'models', 'users', ['owner_id'], ['id'])
    op.drop_column('models', 'endpoint')
    op.drop_column('models', 'version')
    op.drop_column('models', 'status')
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.execute(
        "UPDATE users SET role = 'ADMIN' WHERE role = 'admin'"
    )
    op.execute(
        "UPDATE users SET role = 'USER' WHERE role = 'user'"
    )

    op.execute(
        "ALTER TABLE users ALTER COLUMN role TYPE user_role_enum USING role::user_role_enum"
    )
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'USER', name='user_role_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['username'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='user_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.add_column('models', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('models', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('models', sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_column('models', 'updated_at')
    op.drop_column('models', 'owner_id')
    op.drop_column('models', 'task')
    op.drop_column('models', 'description')
    op.add_column('api_usage', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_usage', type_='foreignkey')
    op.create_foreign_key(op.f('api_usage_model_id_fkey'), 'api_usage', 'models', ['model_id'], ['id'])
    op.drop_column('api_usage', 'updated_at')
    op.drop_column('api_usage', 'model_version_id')
    op.drop_column('api_keys', 'updated_at')
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
