"""Create API key mode

Revision ID: 4f8350fbc33c
Revises: 
Create Date: 2026-06-24 19:49:07.435439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f8350fbc33c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               postgresql_using="id::text::integer")  # Or simply "id::integer" if safe
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="user_id::text::integer")
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    op.drop_column('api_keys', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('api_keys_pkey', 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('api_keys', 'is_active')
    # ### end Alembic commands ###
